version: '3.8'

services:
  discord-logger:
    build: .
    container_name: discord-logger-bot
    restart: unless-stopped
    environment:
      # Discord Configuration
      - logger_discord_token=${logger_discord_token}
      
      # Supabase Configuration
      - supabase_url=${supabase_url}
      - supabase_key=${supabase_key}
      
      # Logging Configuration
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - ENABLE_DEBUG=${ENABLE_DEBUG:-false}
      - LOG_FILE_PATH=/app/logs/discord_logger.log
      
      # Performance Configuration
      - BATCH_SIZE=${BATCH_SIZE:-50}
      - MAX_QUEUE_SIZE=${MAX_QUEUE_SIZE:-10000}
      - FLUSH_INTERVAL=${FLUSH_INTERVAL:-30}
      
      # Backfill Configuration
      - BACKFILL_ENABLED=${BACKFILL_ENABLED:-true}
      - BACKFILL_CHUNK_SIZE=${BACKFILL_CHUNK_SIZE:-100}
      - BACKFILL_DELAY_SECONDS=${BACKFILL_DELAY_SECONDS:-1.0}
      - BACKFILL_MAX_AGE_DAYS=${BACKFILL_MAX_AGE_DAYS:-}
      - BACKFILL_ON_STARTUP=${BACKFILL_ON_STARTUP:-false}
      
      # Filtering Configuration
      - ALLOWED_GUILDS=${ALLOWED_GUILDS:-}
      - IGNORED_GUILDS=${IGNORED_GUILDS:-}
      - ALLOWED_CHANNELS=${ALLOWED_CHANNELS:-}
      - IGNORED_CHANNELS=${IGNORED_CHANNELS:-}
      
      # Message Processing Configuration
      - PROCESS_BOT_MESSAGES=${PROCESS_BOT_MESSAGES:-true}
      - PROCESS_SYSTEM_MESSAGES=${PROCESS_SYSTEM_MESSAGES:-true}
      - PROCESS_DM_MESSAGES=${PROCESS_DM_MESSAGES:-false}
      
      # Health Check Configuration
      - HEALTH_CHECK_ENABLED=${HEALTH_CHECK_ENABLED:-true}
      - HEALTH_CHECK_PORT=${PORT:-8080}
    ports:
      - "${PORT:-8080}:8080"
    volumes:
      - discord-logs:/app/logs
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  discord-logs:
    driver: local 